sources = [
    'src/com/parsebridge/parsebridge/ParseBridgeDeleteCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeSaveCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeGetCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeFindCallback.java',
]

aidl_sources = [
    
]

deps = [
    
]

libs = [
    'libs/Parse-1.3.3.jar'
]

paths = [
    'src',
]

Import('env')
env.BuildJava("Parse/ParseBridge/java", sources, paths, deps, libs=libs, output=True, aidl_sources=aidl_sources)
