sources = [
    'src/com/parsebridge/parsebridge/ParseApplication.java',
    'src/com/parsebridge/parsebridge/ParseReceiverIntent.java',
    'src/com/parsebridge/parsebridge/ParseBridgeDeleteCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeSaveCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeGetCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeFindCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeFunctionCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeRefreshCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeCountCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeLogInCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeSignUpCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeRequestPasswordResetCallback.java',
    'src/com/parsebridge/parsebridge/ParseBridgeTwitterUtilsShim.java',
]

aidl_sources = [
    
]

deps = [
    
]

libs = [
    'libs/Parse-1.3.5.jar'
]

paths = [
    'src',
]

Import('env')
env.BuildJava("Parse/ParseBridge/java", sources, paths, deps, libs=libs, output=True, aidl_sources=aidl_sources)
